#!/bin/bash

echo "[/] Starting..."
sleep 1
echo "..."
sleep 1
fin up > /dev/null 2>&1
echo "..."
sleep 2
echo "[/] Dumping database..."
sleep 1
echo "..."
sleep 1
last_num=$(ls dbdump/staridump*.sql 2>/dev/null | grep -o -E 'staridump([0-9]+)\.sql' | grep -o -E '[0-9]+' | sort -n | tail -1)
next_num=$((last_num + 1))

if [ -f "dbdump/dump.sql" ]; then
	mv dbdump/dump.sql dbdump/"staridump${next_num}.sql"
fi

fin drush sql:dump > dbdump/dump.sql
echo "..."
sleep 2
echo "[\] Dump completed!"
sleep 1
echo "[/] Exporting config..."
sleep 2
echo "..."
fin drush cex -y > /dev/null 2>&1
sleep 1
echo "..."
sleep 2
echo "[\] Config exported!"
sleep 1
echo "[✓] Done!"
