<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_menu_links_discovered_alter().
 * Modify the menu links based on user login status.
 */
function elektronski_dnevnik_menu_links_discovered_alter(array &$links) {
  $current_user = \Drupal::currentUser();

  if ($current_user->isAuthenticated()) {
    // User is logged in, add a Logout link.
    $links['elektronski_dnevnik.logout_link'] = [
      'title' => t('Logout'),
      'route_name' => 'user.logout',
      'menu_name' => 'main-menu',
      'weight' => 0,
    ];
    if (isset($links['elektronski_dnevnik.custom_login_link'])) {
      unset($links['elektronski_dnevnik.custom_login_link']);
    }
  }
  else {
    // User is not logged in, show the Login link.
    $links['elektronski_dnevnik.custom_login_link'] = [
      'title' => t('Login'),
      'route_name' => 'elektronski_dnevnik.login',
      'menu_name' => 'main-menu',
      'weight' => 0,
    ];
    if (isset($links['elektronski_dnevnik.logout_link'])) {
      unset($links['elektronski_dnevnik.logout_link']);
    }
  }

  /**
   * Custom accsess callback to restrict accsess to the class form page.
   */
  function elektronski_dnevnik_class_form_access() {
    $current_user = \Drupal::currentUser();
    $connection = \Drupal::database();
    $user_username = $current_user->getAccountName();

    $query = $connection->select('teachers', 't')
        ->condition('t.username', $user_username, '=')
        ->countQuery()
        ->execute()
        ->fetchField();

    $exists = !empty($query);

    if ($exists) {
      return AccsessResult::allowed();
    } else {
      return AccsessResult::forbidden();
    }
  }
}
